version: '2'
services:

  php:
    image: jguyomard/laravel-php:7.3
    volumes:
      - ./src/api:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=pgsql"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  nginx:
    image: jguyomard/laravel-nginx:1.13
    volumes_from:
      - php
    ports:
      - 8080:80

  pgsql:
    image: postgres:9.6-alpine
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=homestead"
      - "POSTGRES_USER=homestead"
      - "POSTGRES_PASSWORD=homestead"
    ports:
      - "5432:5432"

  elastic:
    image: elasticsearch:5.5-alpine
    ports:
      - "9200:9200"

volumes:
  mysqldata:
  pgsqldata:
