version: '3'
services:

  php:
    build: ./php/7.3
    volumes:
      - ./src/api:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: homestead
      DB_PASSWORD: homestead
      REDIS_HOST: redisdo
      REDIS_PORT: 6379
      XDEBUG_CONFIG: zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20180731/xdebug.so xdebug.remote_enable=1 xdebug.remote_autostart=1 xdebug.remote_connect_back=off xdebug.remote_host=host.docker.internal xdebug.remote_port=9005 xdebug.idekey=PHPSTORM xdebug.max_nesting_level=1500
  nginx:
    image: jguyomard/laravel-nginx:1.13
    volumes:
      - ./src/api:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    ports:
      - 8080:80

  pgsql:
    image: postgres:9.6-alpine
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: laravel
       POSTGRES_USER: homestead
       POSTGRES_PASSWORD: homestead
    ports:
      - 5433:5432

  elastic:
    image: elasticsearch:5.5-alpine
    ports:
      - 9200:9200

volumes:
  mysqldata:
  pgsqldata:
